CREATE TABLE IF NOT EXISTS counter (
  id INTEGER PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS progress (
  userId TEXT PRIMARY KEY,
  data TEXT NOT NULL DEFAULT '{}',
  lastVisit TEXT NOT NULL DEFAULT '',
  streak INTEGER NOT NULL DEFAULT 0
);

INSERT INTO counter (id, value) VALUES (1, 0) ON CONFLICT(id) DO NOTHING;
